setting:
  name: "test_livox"
  output_root: "./experiments"
  pc_path: "/home/irap/dataset/NTU/loop3_livox"
  pose_path: "/home/irap/dataset/NTU/gt_odom/loop3_livox.txt"
process:
  min_range_m: 0.5
  max_range_m: 30.0
  min_z_m: -30.0
  vox_down_m: 0.08
sampler:
  surface_sample_range_m: 0.25 
  surface_sample_n: 4
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 2
neuralpoints:
  voxel_size_m: 0.4
  query_nn_k: 6
  search_alpha: 0.2
  weighted_first: False
loss:
  sigma_sigmoid_m: 0.08
  loss_weight_on: True
  dist_weight_scale: 0.8
  ekional_loss_on: True
  weight_e: 0.5
  numerical_grad_on: True
continual:
  batch_size_cur_frame: 1000
  pool_capacity: 1e7
tracker:
  source_vox_down_m: 0.6
  iter_n: 100
pgo:
  pgo_freq_frame: 20
  context_cosdist: 0.3
optimizer:
  iters: 15
  batch_size: 8192
  adaptive_iters: True
eval:
  o3d_vis_on: False # visualize the mapping or not
  mesh_freq_frame: 20 # reconstruct the mesh every x frames
  mesh_min_nn: 15
  log_freq_frame: 10